AllCops:
  Exclude:
    - 'test/helper.rb'
AbcSize:
  Exclude:
    - 'test/**/*'
AccessorMethodName:
  Exclude:
    - 'lib/mws/**/client.rb'
ClassLength:
  Enabled: false
Documentation:
  Exclude:
    - 'test/**/*'
<<<<<<< HEAD
=======
DotPosition:
  EnforcedStyle: leading
>>>>>>> upstream/master
GlobalVars:
  Exclude:
    - 'test/**/*'
HandleExceptions:
  Exclude:
    - 'test/**/*'
GuardClause:
  Enabled: false
LineLength:
  Exclude:
    - 'test/**/*'
    - 'lib/mws/**/client.rb'
MethodLength:
  Exclude:
    - 'test/**/*'
    - 'lib/mws/**/client.rb'
MultilineMethodCallIndentation:
  EnforcedStyle: indented
ParameterLists:
  Exclude:
    - 'lib/mws/**/client.rb'
<<<<<<< HEAD
=======
StringLiterals:
  EnforcedStyle: single_quotes
>>>>>>> upstream/master
